export const CLUSTERS = {
  A: { name: "Analytical & Technology", color: "#3B82F6", icon: "💻", streams: ["Science (PCM)", "BCA", "B.Tech CS/IT"] },
  B: { name: "Healthcare & Medical", color: "#EF4444", icon: "🏥", streams: ["Science (PCB)", "MBBS", "BDS", "Nursing"] },
  C: { name: "Business & Finance", color: "#F59E0B", icon: "📊", streams: ["Commerce", "BBA", "B.Com", "CA"] },
  D: { name: "Creative & Design", color: "#8B5CF6", icon: "🎨", streams: ["Arts / Humanities", "B.Des", "BFA", "Film Studies"] },
  E: { name: "Law & Civil Services", color: "#6366F1", icon: "⚖️", streams: ["Arts / Humanities", "BA LLB", "UPSC Preparation"] },
  F: { name: "Communication & Media", color: "#EC4899", icon: "🎙️", streams: ["Arts / Humanities", "BJMC", "Mass Communication"] },
  G: { name: "Psychology & Human Behavior", color: "#14B8A6", icon: "🧠", streams: ["Arts / Science", "BA/BSc Psychology", "Counselling"] },
  H: { name: "Core Sciences & Research", color: "#0EA5E9", icon: "🔬", streams: ["Science (PCM/PCB)", "BSc", "Research Programs"] },
  I: { name: "Sports & Performance", color: "#F97316", icon: "🏆", streams: ["Physical Education", "Sports Science", "BPEd"] },
};

export const CLUSTER_DESCRIPTIONS = {
  A: "You thrive on logic, systems, and building solutions. Careers in software engineering, data science, AI, and product development await.",
  B: "You care deeply about health and healing. Medicine, surgery, pharmacy, physiotherapy, and biomedical research are your path.",
  C: "You think in terms of growth, opportunity, and value creation. Finance, entrepreneurship, consulting, and management are natural fits.",
  D: "You see the world through a creative lens. Design, filmmaking, animation, branding, and creative direction fuel your passion.",
  E: "You value justice, governance, and structured authority. Law, civil services, policy-making, and public administration suit you.",
  F: "You love being heard and shaping narratives. Journalism, content creation, PR, advertising, and broadcasting match your energy.",
  G: "You read people well and care about emotional wellbeing. Clinical psychology, counselling, HR, and behavioral research are ideal.",
  H: "You question how the world works at a fundamental level. Research science, academia, space science, and advanced R&D call you.",
  I: "You push physical limits and thrive on competition. Professional sports, coaching, sports management, and fitness training are your arena.",
};

// Q1, Q6, Q12 carry double weight
export const DOUBLE_WEIGHT_QUESTIONS = [0, 5, 11]; // 0-indexed

export const questions = [
  {
    id: 1,
    text: "Which subject genuinely energizes you?",
    options: [
      { key: "A", text: "Mathematics / Coding" },
      { key: "B", text: "Biology / Human Body" },
      { key: "C", text: "Business / Economics" },
      { key: "D", text: "Art / Design" },
      { key: "E", text: "Political Science / Civics" },
      { key: "F", text: "Media / Communication" },
      { key: "G", text: "Psychology" },
      { key: "H", text: "Physics / Chemistry theory" },
      { key: "I", text: "Sports / Physical training" },
    ],
  },
  {
    id: 2,
    text: "When facing a difficult problem, you instinctively:",
    options: [
      { key: "A", text: "Break it down logically" },
      { key: "B", text: "Think about physical impact on people" },
      { key: "C", text: "Evaluate financial outcomes" },
      { key: "D", text: "Reimagine it creatively" },
      { key: "E", text: "Consider legal or ethical angles" },
      { key: "F", text: "Think about how to communicate it" },
      { key: "G", text: "Understand emotional dynamics" },
      { key: "H", text: "Examine scientific principles" },
      { key: "I", text: "Focus on execution and performance" },
    ],
  },
  {
    id: 3,
    text: "Your YouTube feed mostly shows:",
    options: [
      { key: "A", text: "Coding / Tech Explainers" },
      { key: "B", text: "Medical / Health videos" },
      { key: "C", text: "Startup / Investing content" },
      { key: "D", text: "Design / Filmmaking" },
      { key: "E", text: "Law / Policy / Debates" },
      { key: "F", text: "Podcasts / Commentary" },
      { key: "G", text: "Human behavior breakdowns" },
      { key: "H", text: "Science documentaries" },
      { key: "I", text: "Sports highlights / training" },
    ],
  },
  {
    id: 4,
    text: "Teachers usually describe you as:",
    options: [
      { key: "A", text: "Analytical" },
      { key: "B", text: "Compassionate" },
      { key: "C", text: "Driven" },
      { key: "D", text: "Creative" },
      { key: "E", text: "Argumentative (in a good way)" },
      { key: "F", text: "Expressive" },
      { key: "G", text: "Observant" },
      { key: "H", text: "Deep thinker" },
      { key: "I", text: "Competitive" },
    ],
  },
  {
    id: 5,
    text: "Which achievement would make you happiest?",
    options: [
      { key: "A", text: "Building a working system" },
      { key: "B", text: "Helping someone recover" },
      { key: "C", text: "Scaling a profitable venture" },
      { key: "D", text: "Creating something original" },
      { key: "E", text: "Winning a debate" },
      { key: "F", text: "Growing an audience" },
      { key: "G", text: "Helping someone emotionally" },
      { key: "H", text: "Publishing research" },
      { key: "I", text: "Winning a tournament" },
    ],
  },
  {
    id: 6,
    text: "If success was guaranteed, you would choose to:",
    options: [
      { key: "A", text: "Build breakthrough technology" },
      { key: "B", text: "Become a top surgeon" },
      { key: "C", text: "Run a large company" },
      { key: "D", text: "Direct films / brands" },
      { key: "E", text: "Become a judge / top civil servant" },
      { key: "F", text: "Host a national show" },
      { key: "G", text: "Run a therapy practice" },
      { key: "H", text: "Become a leading scientist" },
      { key: "I", text: "Play professional sport" },
    ],
  },
  {
    id: 7,
    text: "You prefer working in:",
    options: [
      { key: "A", text: "Tech lab" },
      { key: "B", text: "Hospital" },
      { key: "C", text: "Corporate office" },
      { key: "D", text: "Studio" },
      { key: "E", text: "Court / Government office" },
      { key: "F", text: "Newsroom" },
      { key: "G", text: "Counseling room" },
      { key: "H", text: "Research lab" },
      { key: "I", text: "Training ground" },
    ],
  },
  {
    id: 8,
    text: "How comfortable are you with long study cycles (8+ years)?",
    options: [
      { key: "A", text: "Comfortable if technical" },
      { key: "B", text: "Yes, if medical" },
      { key: "C", text: "Only if ROI is strong" },
      { key: "D", text: "Prefer skill-based growth" },
      { key: "E", text: "If it leads to authority" },
      { key: "F", text: "Depends on visibility" },
      { key: "G", text: "If it enables practice" },
      { key: "H", text: "Yes, for research" },
      { key: "I", text: "Prefer skill training over academics" },
    ],
  },
  {
    id: 9,
    text: "Your risk tolerance:",
    options: [
      { key: "A", text: "Calculated technical risk" },
      { key: "B", text: "Moderate" },
      { key: "C", text: "High financial risk" },
      { key: "D", text: "Creative risk is fine" },
      { key: "E", text: "Prefer structured authority roles" },
      { key: "F", text: "Risky but high visibility" },
      { key: "G", text: "Low, prefer stability" },
      { key: "H", text: "Low, prefer academic stability" },
      { key: "I", text: "High physical risk tolerance" },
    ],
  },
  {
    id: 10,
    text: "What drives you most?",
    options: [
      { key: "A", text: "Solving complexity" },
      { key: "B", text: "Healing impact" },
      { key: "C", text: "Wealth creation" },
      { key: "D", text: "Creative expression" },
      { key: "E", text: "Power & governance" },
      { key: "F", text: "Influence & reach" },
      { key: "G", text: "Emotional transformation" },
      { key: "H", text: "Discovery & knowledge" },
      { key: "I", text: "Competition & performance" },
    ],
  },
  {
    id: 11,
    text: "In group work, you usually:",
    options: [
      { key: "A", text: "Handle technical backend" },
      { key: "B", text: "Ensure wellbeing" },
      { key: "C", text: "Lead strategy" },
      { key: "D", text: "Design visuals" },
      { key: "E", text: "Frame arguments" },
      { key: "F", text: "Present confidently" },
      { key: "G", text: "Resolve conflicts" },
      { key: "H", text: "Validate facts" },
      { key: "I", text: "Execute under pressure" },
    ],
  },
  {
    id: 12,
    text: "At age 35, you see yourself as:",
    options: [
      { key: "A", text: "CTO or tech founder" },
      { key: "B", text: "Specialist doctor" },
      { key: "C", text: "Investor or CEO" },
      { key: "D", text: "Creative director" },
      { key: "E", text: "Civil servant or judge" },
      { key: "F", text: "Media personality" },
      { key: "G", text: "Licensed psychologist" },
      { key: "H", text: "Senior scientist" },
      { key: "I", text: "Professional coach / athlete" },
    ],
  },
  {
    id: 13,
    text: "Which competition excites you most?",
    options: [
      { key: "A", text: "Hackathon" },
      { key: "B", text: "Medical quiz" },
      { key: "C", text: "Business pitch" },
      { key: "D", text: "Design contest" },
      { key: "E", text: "Debate competition" },
      { key: "F", text: "Content creation challenge" },
      { key: "G", text: "Behavioral case study" },
      { key: "H", text: "Science olympiad" },
      { key: "I", text: "Sports tournament" },
    ],
  },
  {
    id: 14,
    text: "Which impact feels most meaningful?",
    options: [
      { key: "A", text: "Making systems efficient" },
      { key: "B", text: "Saving lives" },
      { key: "C", text: "Creating economic growth" },
      { key: "D", text: "Inspiring creativity" },
      { key: "E", text: "Changing policy" },
      { key: "F", text: "Shaping public opinion" },
      { key: "G", text: "Improving mental health" },
      { key: "H", text: "Advancing knowledge" },
      { key: "I", text: "Inspiring through sport" },
    ],
  },
  {
    id: 15,
    text: "Which statement sounds most like you?",
    options: [
      { key: "A", text: "I love structured logic" },
      { key: "B", text: "I care deeply about health" },
      { key: "C", text: "I think in terms of opportunity" },
      { key: "D", text: "I see the world visually" },
      { key: "E", text: "I enjoy governance and debate" },
      { key: "F", text: "I enjoy being heard" },
      { key: "G", text: "I read people well" },
      { key: "H", text: "I question how the universe works" },
      { key: "I", text: "I push my physical limits" },
    ],
  },
];
